Repository IgniteUI/ignite-ui, pull requests merged in 2018-03, with the labels that each got.

#1626 add templates
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.1

#1633 add main grid style
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.1

#1635 1634 - igTree checkStateChanging trigger on events
  src/js/modules/infragistics.ui.tree.js
  tests/unit/tree/tests.htm
Labels: status: verified, version: 17.1

#1499 Fixing bug 247461
  src/js/modules/i18n/infragistics.ui.notifier-es.js
Labels: status: not-fixed, version: 17.2

#1542 Fixing bug 247461
  src/js/modules/i18n/infragistics.ui.notifier-es.js
Labels: version: 18.1

#1641 Styling for the financial chart sample
  src/css/structure/images/igGrid/indicators-icon-on.svg
  src/css/structure/images/igGrid/indicators-icon.svg
  src/css/structure/images/igGrid/overlay-icon-on.svg
  src/css/structure/images/igGrid/overlay-icon.svg
  src/css/structure/modules/infragistics.ui.financialchart.css
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: status: verified, visual-design

#1644 igToolbar, igToolbarButton and igSplitButton tests
  tests/unit/splitbutton/splitbutton-test.js
  tests/unit/splitbutton/tests.html
  tests/unit/toolbar/tests.html
  tests/unit/toolbar/toolbar-test.js
  tests/unit/toolbarbutton/tests.html
  tests/unit/toolbarbutton/toolbarbtn-test.js
Labels: tests, toolbar, toolbar-button

#1643 #1358 - igDatePicker regional fallback to global regional
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/datePicker/tests.html
Labels: status: verified, version: 18.1

#1642 #1358 - igDatePicker regional fallback to global regional
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/datePicker/tests.html
Labels: status: verified, version: 17.2

#1636 Fix and test for bug 248224
  src/js/modules/infragistics.datasource.js
  tests/unit/dataSource/groupby/tests.html
Labels: status: verified, version: 17.1

#1637 Fix and test for bug 248224
  src/js/modules/infragistics.datasource.js
  tests/unit/dataSource/groupby/tests.html
Labels: status: verified, version: 17.2

#1632 Fix for bug 245327
  src/js/modules/infragistics.ui.scroll.js
  tests/unit/scroll/tests.html
Labels: status: verified, version: 18.1

#1640 Fix for bug 245327. Merge 17.2
  src/js/modules/infragistics.ui.scroll.js
  tests/unit/scroll/tests.html
Labels: status: verified, version: 17.2

#1645 Adding igFinanacialChart to igLoader
  src/js/infragistics.loader.js
Labels: loader, version: 18.1

#1638 Fix and test for bug 248224
  src/js/modules/infragistics.datasource.js
  tests/unit/dataSource/groupby/tests.html
Labels: status: verified, version: 18.1

#1588 Fix icons are not styled correctly when igGrid is used in igSplitter
  src/css/themes/bootstrap3/default/icons-styles.css
  src/css/themes/bootstrap3/flatly/icons-styles.css
  src/css/themes/bootstrap3/superhero/icons-styles.css
  src/css/themes/bootstrap3/yeti/icons-styles.css
  src/css/themes/bootstrap4/default/icons-styles.css
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics2012/icons-styles.css
  src/css/themes/ios/icons-styles.css
  src/css/themes/metro/icons-styles.css
Labels: bug, grid, splitter, status: verified, styling, version: 18.1

#1649 Fix for 17.2
  src/css/themes/bootstrap3/default/icons-styles.css
  src/css/themes/bootstrap3/flatly/icons-styles.css
  src/css/themes/bootstrap3/superhero/icons-styles.css
  src/css/themes/bootstrap3/yeti/icons-styles.css
  src/css/themes/bootstrap4/default/icons-styles.css
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics2012/icons-styles.css
  src/css/themes/ios/icons-styles.css
  src/css/themes/metro/icons-styles.css
Labels: bug, grid, splitter, status: in-test, status: verified, styling, version: 17.2

#1543 Fixing bug 248337
  src/css/structure/modules/infragistics.ui.grid.css
Labels: status: verified, version: 18.1

#1561 Fix unable to scroll down using small movement on touchpad in igScroll
  src/js/modules/infragistics.ui.scroll.js
Labels: status: verified, version: 18.1

#1652 Fixing igSplitter AMD
  src/js/modules/infragistics.ui.splitter.js
Labels: amd, bug, splitter, version: 18.1

#1653 Fixing igSplitter AMD 17.2
  src/js/modules/infragistics.ui.splitter.js
Labels: amd, bug, splitter, version: 17.2

#1659 Fix issue in getDate for dates on the day of a daylight savings change
  src/js/modules/infragistics.util.js
  tests/unit/util/tests.html
Labels: status: verified, version: 18.1

#1654 Fix financialchart loader entries
  src/js/infragistics.loader.js
Labels: status: verified, version: 18.1

#1650 Fix for bug #250102 - Adding IE specific scroll delta check.
  src/js/modules/infragistics.ui.scroll.js
Labels: bug, scroll, status: verified, version: 17.2

#1648 17.1 - TFS249240/249438 - When the chart is destroyed, we should unhook the …
  src/js/modules/infragistics.util.js
Labels: status: verified, version: 17.1

#1646 TFS249240/249438 - When the chart is destroyed, we should unhook the …
  src/js/modules/infragistics.util.js
Labels: status: verified, version: 18.1

#1647 17.2 - TFS249240/249438 - When the chart is destroyed, we should unhook the …
  src/js/modules/infragistics.util.js
Labels: status: verified, version: 17.2

#1663 fix financial chart css
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.1

#1665 Embedded svg icons
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: visual-design

#1669 use position: relative on drop down arrows so they allocate space
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.1

#1671 Adding ig.util.ajax function in the infragistics.util.jquery.js file
  src/js/modules/infragistics.util.jquery.js
Labels: status: verified, util, version: 18.1

#1662 igHtmlEditor test update
  tests/unit/htmleditor/basicfunctionalities/rendering/htmleditor-test.js
  tests/unit/htmleditor/basicfunctionalities/rendering/tests.html
Labels: html-editor, tests

#1672 Fix for bug 251197 Scrollbar between two synced igScroll do not sync when scrolling on touch.
  src/js/modules/infragistics.ui.scroll.js
Labels: scroll, status: verified, version: 18.1

#1656 Fix missing border-bottom on :hover inside igGrid row
  src/css/themes/bootstrap3/default/infragistics.theme.css
  src/css/themes/bootstrap3/default/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/flatly/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/bootstrap4/default/modules/_infragistics.ui.grid.scss
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/modules/infragistics.ui.grid.less
Labels: grid, status: verified, styling, version: 18.1

#1658 fix igGrid header and body are misaligned in 17.1
  src/css/structure/modules/infragistics.ui.grid.css
  src/css/themes/bootstrap3/_shared-styles/less/infragistics.igniteui.theme.less
  src/css/themes/bootstrap3/_shared-styles/less/infragistics.jqueryui.theme.less
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap4/_shared-styles/scss/_infragistics.igniteui.theme.scss
  src/css/themes/bootstrap4/infragistics.theme.css
  src/css/themes/bootstrap4/infragistics.theme.css.map
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/infragistics.theme.less
Labels: grid, status: verified, styling, version: 17.1

#1660 fix igGrid header and body are misaligned in 17.2
  src/css/structure/modules/infragistics.ui.grid.css
  src/css/themes/bootstrap3/default/infragistics.theme.css
  src/css/themes/bootstrap3/default/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/flatly/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/bootstrap4/default/modules/_infragistics.ui.grid.scss
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/modules/infragistics.ui.grid.less
Labels: grid, status: verified, styling, version: 17.2

#1661 fix igGrid header and body are misaligned in 18.1
  src/css/structure/modules/infragistics.ui.grid.css
  src/css/themes/bootstrap3/default/infragistics.theme.css
  src/css/themes/bootstrap3/default/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/flatly/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/bootstrap4/default/modules/_infragistics.ui.grid.scss
Labels: grid, status: verified, styling, version: 18.1

#1679 Update editors references
  src/js/infragistics.loader.js
  src/js/modules/infragistics.ui.editors.js
  tests/unit/loader/tests.html
Labels: editors, refactoring, status: awaiting-test, version: 17.1

#1678 Update editors references
  src/js/infragistics.loader.js
  src/js/modules/infragistics.ui.editors.js
  tests/unit/loader/tests.html
Labels: editors, refactoring, status: awaiting-test, version: 17.2

#1676 Update editors references
  src/js/infragistics.loader.js
  src/js/modules/infragistics.ui.editors.js
  tests/unit/loader/tests.html
Labels: editors, refactoring, status: awaiting-test, version: 18.1

#1674 Fix for bug 251152: The filtering editor's text is cut off when the c…
  src/css/structure/modules/infragistics.ui.grid.css
Labels: grid, status: verified, version: 18.1

#1682 Update npm deploy tag 17.2
  .travis.yml
Labels: build, npm, version: 17.2

#1680 Update npm deploy tag
  .travis.yml
Labels: build, npm, version: 18.1

#1681 Update npm deploy tag 17.1
  .travis.yml
Labels: build, npm, version: 17.1

#1684 Change jQuery + UI packages to peer dependency
  build/packages/package.json
Labels: npm, status: verified, version: 17.2

#1689 1673 - igMaskEditor - revertValue retains mask - 17.2
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/maskEditor/tests.html
Labels: status: verified, version: 17.2

#1687 1673 - igMaskEditor - revertValue retains mask
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/maskEditor/tests.html
Labels: status: verified, version: 18.1

#1683 Adding additional styling for the ui-igspreadsheet-filter-dialog
  src/css/structure/modules/infragistics.ui.spreadsheet.css
Labels: status: verified, styling, version: 18.1

#1685 Change jQuery + UI packages to peer dependency
  build/packages/package.json
Labels: npm, version: 18.1
