Repository IgniteUI/ignite-ui, pull requests merged in 2018-09, with the labels that each got.

#1784 currentTime moves as expected
  src/js/modules/infragistics.ui.videoplayer.js
Labels: status: verified, version: 18.2, video-player

#1785 currentTime moves as expected - 17.2
  src/js/modules/infragistics.ui.videoplayer.js
Labels: status: verified, version: 17.2, video-player

#1786 currentTime moves as expected - 18.1
  src/js/modules/infragistics.ui.videoplayer.js
Labels: status: verified, version: 18.1, video-player

#1789 TFS256959 use Intl to get am and pm designators
  src/js/modules/infragistics.util.js
Labels: status: verified, version: 18.2

#1787 Fix styling issues regarding alignment and height
  src/css/structure/modules/infragistics.ui.grid.css
Labels: grid, status: verified, styling

#1790 Add Inline SVG
  src/css/structure/modules/infragistics.ui.financialchart.css
  src/css/themes/bootstrap3/default/icons-styles.css
  src/css/themes/bootstrap3/default/infragistics.theme.css
  src/css/themes/bootstrap3/default/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/bootstrap3/flatly/icons-styles.css
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/flatly/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/bootstrap3/superhero/icons-styles.css
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/bootstrap3/yeti/icons-styles.css
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/bootstrap4/default/icons-styles.css
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/bootstrap4/default/modules/_infragistics.ui.chart.toolbar.scss
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/infragistics.theme.less
  src/css/themes/infragistics/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/infragistics2012/icons-styles.css
  src/css/themes/infragistics2012/infragistics.theme.css
  src/css/themes/infragistics2012/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/ios/icons-styles.css
  src/css/themes/ios/infragistics.theme.css
  src/css/themes/ios/infragistics.theme.less
  src/css/themes/ios/modules/infragistics.ui.chart.toolbar.less
  src/css/themes/metro/icons-styles.css
  src/css/themes/metro/infragistics.theme.css
  src/css/themes/metro/modules/infragistics.ui.chart.toolbar.less
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: status: verified, styling, themes

#1793 style(filter dialog and menu)Fix separator and filter dialog styling
  src/css/structure/modules/infragistics.ui.spreadsheet.css
  src/css/themes/bootstrap3/default/infragistics.theme.css
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics2012/infragistics.theme.css
  src/css/themes/ios/infragistics.theme.css
  src/css/themes/metro/infragistics.theme.css
Labels: dialog, enhancement, styling

#1794 Fix for tfs 251906 18.2
  src/css/structure/modules/infragistics.ui.financialchart.css
  src/css/structure/modules/infragistics.ui.spreadsheet.css
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
Labels: dialog, enhancement, styling

#1795 Fix for 1757 18.1
  src/css/themes/metro/infragistics.theme.css
  src/css/themes/metro/modules/infragistics.ui.grid.less
Labels: status: verified, styling, version: 18.1

#1796 Fix for 1757 18.2
  src/css/themes/metro/infragistics.theme.css
  src/css/themes/metro/modules/infragistics.ui.grid.less
Labels: status: verified, styling, version: 18.2

#1797 Change icon for delete row/col and clear content
  src/css/themes/bootstrap3/default/icons-styles.css
  src/css/themes/bootstrap3/flatly/icons-styles.css
  src/css/themes/bootstrap3/superhero/icons-styles.css
  src/css/themes/bootstrap3/yeti/icons-styles.css
  src/css/themes/bootstrap4/default/icons-styles.css
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics2012/icons-styles.css
  src/css/themes/ios/icons-styles.css
  src/css/themes/metro/icons-styles.css
Labels: status: verified, styling, version: 18.1

#1798 Change icons 18.2
  src/css/themes/bootstrap3/default/icons-styles.css
  src/css/themes/bootstrap3/flatly/icons-styles.css
  src/css/themes/bootstrap3/superhero/icons-styles.css
  src/css/themes/bootstrap3/yeti/icons-styles.css
  src/css/themes/bootstrap4/default/icons-styles.css
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics2012/icons-styles.css
  src/css/themes/ios/icons-styles.css
  src/css/themes/metro/icons-styles.css
Labels: status: verified, styling, version: 18.2

#1792 Fix the cut icons arrows for spinner buttons
  src/css/structure/modules/infragistics.ui.spreadsheet.css
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/modules/infragistics.ui.spreadsheet.less
Labels: status: verified, styling, version: 18.2

#1791 Fix the cut icons arrows for spinner buttons
  src/css/structure/modules/infragistics.ui.spreadsheet.css
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/infragistics/icons-styles.css
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/modules/infragistics.ui.spreadsheet.less
Labels: status: verified, styling, version: 18.1

#1800 fully urlencode svg
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.2

#1802 Fixed the styling for the custom sort dialog
  src/css/structure/modules/infragistics.ui.spreadsheet.css
Labels: status: verified, styling, version: 18.2

#1805 #1804 Remove redundant edit value cache on keydown
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/tests.html
  tests/unit/editors/baseEditor/tests.html
Labels: status: verified, version: 17.2

#1806 #1804 Remove redundant edit value cache on keydown
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/tests.html
  tests/unit/editors/baseEditor/tests.html
Labels: status: verified, version: 18.1

#1807 #1804 Remove redundant edit value cache on keydown
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/bugs-test.js
  tests/unit/editors/baseEditor/base-test.js
Labels: status: verified, version: 18.2

#1808 #1695 Prevent parsing invalid date produced with IME input
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/tests.html
  tests/unit/editors/numericEditor/tests.html
Labels: datepicker, editors, ime, numeric-editor, status: verified, version: 17.2

#1811 #1776 [igEditors] add input handler for auto-fill
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/tests.html
Labels: editors, status: verified, version: 17.2

#1812 #1776 [igEditors] add input handler for auto-fill
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/tests.html
Labels: editors, status: verified, version: 18.1

#1813 #1776 [igEditors] add input handler for auto-fill
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/Bugs/bugs-test.js
Labels: editors, status: verified, version: 18.2
