Repository IgniteUI/ignite-ui, pull requests merged in 2018-06, with the labels that each got.

#1736 replace indicator picker with indicator menu
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.2

#1739 Datepicker formating/calendar sync 18.1
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/DatePickerBugs/tests.html
Labels: datepicker, enhancement, status: verified, version: 18.1

#1740 Datepicker formating/calendar sync 18.2
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/DatePickerBugs/datePickerBugs-test.js
Labels: datepicker, enhancement, status: verified, tests, version: 18.2

#1738 Datepicker formating/calendar sync 17.2
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/DatePickerBugs/tests.html
Labels: datepicker, enhancement, status: verified, tests, version: 17.2

#1735 #1733 Datepicker formating/calendar sync 17.1
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/DatePickerBugs/tests.html
Labels: datepicker, status: verified, version: 17.1

#1737 update templates for new toolbar
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: version: 18.2

#1742 corrections to templates, remove dead templates
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: status: verified, version: 18.2

#1743 styling new toolbar
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.2

#1744 add financial chart legend
  src/css/structure/modules/infragistics.ui.financialchart.css
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: version: 18.2
