Repository IgniteUI/ignite-ui, pull requests merged in 2018-02, with the labels that each got.

#1562 Fixes for TFS bug 244818
  src/js/modules/i18n/infragistics.ui.htmleditor-bg.js
  src/js/modules/i18n/infragistics.ui.htmleditor-de.js
  src/js/modules/i18n/infragistics.ui.htmleditor-en.js
  src/js/modules/i18n/infragistics.ui.htmleditor-es.js
  src/js/modules/i18n/infragistics.ui.htmleditor-fr.js
  src/js/modules/i18n/infragistics.ui.htmleditor-ja.js
  src/js/modules/i18n/infragistics.ui.htmleditor-ru.js
Labels: html-editor, status: verified, version: 18.1

#1589 disable input field when igCombo is disabled
  src/js/modules/infragistics.ui.combo.js
  tests/unit/combo/rendering/tests.html
  tests/unit/combo/test-shared.js
Labels: status: verified

#1593 Fixes for TFS bug 244818
  src/js/modules/i18n/infragistics.ui.htmleditor-bg.js
  src/js/modules/i18n/infragistics.ui.htmleditor-de.js
  src/js/modules/i18n/infragistics.ui.htmleditor-en.js
  src/js/modules/i18n/infragistics.ui.htmleditor-es.js
  src/js/modules/i18n/infragistics.ui.htmleditor-fr.js
  src/js/modules/i18n/infragistics.ui.htmleditor-ja.js
  src/js/modules/i18n/infragistics.ui.htmleditor-ru.js
Labels: bug, html-editor, status: verified

#1592 Added two entries for timepicker
  src/js/modules/i18n/infragistics.ui.editors-bg.js
  src/js/modules/i18n/infragistics.ui.editors-de.js
  src/js/modules/i18n/infragistics.ui.editors-es.js
  src/js/modules/i18n/infragistics.ui.editors-fr.js
  src/js/modules/i18n/infragistics.ui.editors-ja.js
  src/js/modules/i18n/infragistics.ui.editors-ru.js
Labels: status: localized, status: verified

#1595 #1391 Stop current dialog animation before destroy
  src/js/modules/infragistics.ui.dialog.js
  tests/unit/dialog/tests.html
Labels: status: verified, version: 17.1

#1596 #1391 Stop current dialog animation before destroy
  src/js/modules/infragistics.ui.dialog.js
  tests/unit/dialog/tests.html
Labels: status: verified, version: 17.2

#1597 #1391 Stop current dialog animation before destroy
  src/js/modules/infragistics.ui.dialog.js
  tests/unit/dialog/tests.html
Labels: status: verified, version: 18.1

#1591 Refactoring scroll tests
  karma.conf.js
  tests/unit/common/simInteractions.js
  tests/unit/scroll/events/events-test.js
  tests/unit/scroll/events/tests.html
  tests/unit/scroll/navigation/navigation-test.js
  tests/unit/scroll/navigation/tests.html
  tests/unit/scroll/scroll-test.js
  tests/unit/scroll/tests.html
Labels: refactoring, tests

#1599 Exclude i18n folder from coverage report.
  karma.conf.js
Labels: coverage, tests

#1606 add ie11 grid layout properties
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.1

#1603 #1566 VideoPlayer destroy removes the tooltip correctly
  src/js/modules/infragistics.ui.shared.js
  tests/unit/videoplayer/tests.html
Labels: status: verified, version: 18.1

#1608 #1362 Escape unicode characters in maskEditor validate
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/maskEditor/tests.html
Labels: status: verified, version: 18.1

#1619 #1594 Toggle the full screen mode css class based on the option value
  src/js/modules/infragistics.ui.videoplayer.js
  tests/unit/videoplayer/tests.html
Labels: status: verified, version: 18.1

#1611 #1204 Changing open and close animation handling for igDialog
  src/js/modules/infragistics.ui.dialog.js
  tests/unit/dialog/tests.html
Labels: status: verified, version: 17.1

#1612 #1204 Changing open and close animation handling for igDialog
  src/js/modules/infragistics.ui.dialog.js
  tests/unit/dialog/tests.html
Labels: status: verified, version: 17.2

#1613 #1204 Changing open and close animation handling for igDialog
  src/js/modules/infragistics.ui.dialog.js
  tests/unit/dialog/tests.html
Labels: status: verified, version: 18.1

#1616 #1609: igDatePicker onChangeMonthYear event pass args
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/datePicker/tests.html
Labels: status: verified, version: 18.1

#1617 #1609: igDatePicker onChangeMonthYear event pass args
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/datePicker/tests.html
Labels: status: verified, version: 17.2

#1618 #1609: igDatePicker onChangeMonthYear event pass args
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/datePicker/tests.html
Labels: status: verified, version: 17.1

#1620 #1571 - ignumericeditor dropdown scrollbar fix
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/numericEditor/tests.html
Labels: status: verified, version: 18.1

#1621 VideoPlayerTests_toggle full-screen-mode css class
  tests/unit/videoplayer/videoplayer-test.js
Labels: tests, video-player

#1614 modify financial chart range selector template so labels are easier t…
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: status: verified, version: 18.1

#1615 modify range selector last option class
  src/css/structure/modules/infragistics.ui.financialchart.css
Labels: status: verified, version: 18.1

#1622 Spreadsheet depends on igDialog as of 18.1
  src/js/infragistics.loader.js
Labels: spreadsheet, status: verified, version: 18.1

#1624 rename indicator
  src/html/structure/modules/infragistics.ui.financialchart.templates.html
Labels: status: verified, version: 18.1

#1628 Fix bug master #1627
  src/js/modules/infragistics.ui.combo.js
Labels: combo, status: verified, version: 18.1

#1631 fix bug 1627
  src/js/modules/infragistics.ui.combo.js
Labels: combo, status: verified, version: 17.1

#1629 fix bug #1627
  src/js/modules/infragistics.ui.combo.js
Labels: combo, status: verified, version: 17.2
