Repository IgniteUI/ignite-ui, pull requests merged in 2018-04, with the labels that each got.

#1691 fix loader issues with categorychart and shapechart 18.1
  src/js/infragistics.loader.js
Labels: status: verified, version: 18.1

#1694 API snippets now use jQuery "On" method instead of deprecated "Delegate"
  src/js/modules/infragistics.ui.colorpicker.js
  src/js/modules/infragistics.ui.combo.js
  src/js/modules/infragistics.ui.dialog.js
  src/js/modules/infragistics.ui.editors.js
  src/js/modules/infragistics.ui.htmleditor.js
  src/js/modules/infragistics.ui.layoutmanager.js
  src/js/modules/infragistics.ui.popover.js
  src/js/modules/infragistics.ui.rating.js
  src/js/modules/infragistics.ui.scroll.js
  src/js/modules/infragistics.ui.splitbutton.js
  src/js/modules/infragistics.ui.splitter.js
  src/js/modules/infragistics.ui.tilemanager.js
  src/js/modules/infragistics.ui.toolbar.js
  src/js/modules/infragistics.ui.toolbarbutton.js
  src/js/modules/infragistics.ui.tree.js
  src/js/modules/infragistics.ui.upload.js
  src/js/modules/infragistics.ui.validator.js
  src/js/modules/infragistics.ui.videoplayer.js
  src/js/modules/infragistics.ui.zoombar.js
Labels: documentation, status: verified, version: 17.2

#1693 API snippets now use jQuery "On" method instead of deprecated "Delegate"
  src/js/modules/infragistics.ui.colorpicker.js
  src/js/modules/infragistics.ui.combo.js
  src/js/modules/infragistics.ui.dialog.js
  src/js/modules/infragistics.ui.editors.js
  src/js/modules/infragistics.ui.htmleditor.js
  src/js/modules/infragistics.ui.layoutmanager.js
  src/js/modules/infragistics.ui.popover.js
  src/js/modules/infragistics.ui.rating.js
  src/js/modules/infragistics.ui.scroll.js
  src/js/modules/infragistics.ui.splitbutton.js
  src/js/modules/infragistics.ui.splitter.js
  src/js/modules/infragistics.ui.tilemanager.js
  src/js/modules/infragistics.ui.toolbar.js
  src/js/modules/infragistics.ui.toolbarbutton.js
  src/js/modules/infragistics.ui.tree.js
  src/js/modules/infragistics.ui.upload.js
  src/js/modules/infragistics.ui.validator.js
  src/js/modules/infragistics.ui.videoplayer.js
  src/js/modules/infragistics.ui.zoombar.js
Labels: documentation, status: verified, version: 18.1

#1700 Updating the multiple upload sample to include the single request upload option.
  demos/file-upload/multiple-upload.html
Labels: demos, upload, version: 18.1

#1698 Add time-picker to demos folder
  demos/editors/time-picker.html
Labels: demos, timepicker, version: 18.1

#1686 Implement support for "time" columns
  src/js/modules/infragistics.datasource.js
  src/js/modules/infragistics.ui.editors.js
  src/js/modules/infragistics.util.jquery.js
  src/js/modules/infragistics.util.js
  tests/unit/dataSource/filtering/tests.html
  tests/unit/dataSource/sorting/tests.html
  tests/unit/util/tests.html
Labels: status: verified, timepicker, version: 18.1

#1675 Merging 18.1 into master
  .travis.yml
  build/packages/package.json
  demos/editors/time-picker.html
  demos/file-upload/multiple-upload.html
  src/css/structure/modules/infragistics.ui.grid.css
  src/css/structure/modules/infragistics.ui.spreadsheet.css
  src/css/themes/bootstrap3/default/infragistics.theme.css
  src/css/themes/bootstrap3/default/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/flatly/infragistics.theme.css
  src/css/themes/bootstrap3/flatly/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/superhero/infragistics.theme.css
  src/css/themes/bootstrap3/superhero/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap3/yeti/infragistics.theme.css
  src/css/themes/bootstrap3/yeti/modules/infragistics.ui.grid.less
  src/css/themes/bootstrap4/default/infragistics.theme.css
  src/css/themes/bootstrap4/default/infragistics.theme.css.map
  src/css/themes/bootstrap4/default/modules/_infragistics.ui.grid.scss
  src/css/themes/infragistics/infragistics.theme.css
  src/css/themes/infragistics/modules/infragistics.ui.grid.less
  src/js/infragistics.loader.js
  src/js/modules/infragistics.datasource.js
  src/js/modules/infragistics.ui.colorpicker.js
  src/js/modules/infragistics.ui.combo.js
  src/js/modules/infragistics.ui.dialog.js
  src/js/modules/infragistics.ui.editors.js
  src/js/modules/infragistics.ui.htmleditor.js
  src/js/modules/infragistics.ui.layoutmanager.js
  src/js/modules/infragistics.ui.popover.js
  src/js/modules/infragistics.ui.rating.js
  src/js/modules/infragistics.ui.scroll.js
  src/js/modules/infragistics.ui.splitbutton.js
  src/js/modules/infragistics.ui.splitter.js
  src/js/modules/infragistics.ui.tilemanager.js
  src/js/modules/infragistics.ui.toolbar.js
  src/js/modules/infragistics.ui.toolbarbutton.js
  src/js/modules/infragistics.ui.tree.js
  src/js/modules/infragistics.ui.upload.js
  src/js/modules/infragistics.ui.validator.js
  src/js/modules/infragistics.ui.videoplayer.js
  src/js/modules/infragistics.ui.zoombar.js
  src/js/modules/infragistics.util.jquery.js
  src/js/modules/infragistics.util.js
  tests/unit/dataSource/filtering/tests.html
  tests/unit/dataSource/sorting/tests.html
  tests/unit/editors/Bugs/tests.html
  tests/unit/editors/maskEditor/tests.html
  tests/unit/loader/tests.html
  tests/unit/util/tests.html
Labels: version: 18.2

#1692 igCombo test update
  karma.conf.js
  tests/unit/combo/api/api-test.js
  tests/unit/combo/api/tests.html
  tests/unit/combo/binding/binding-test.js
  tests/unit/combo/binding/tests.html
  tests/unit/combo/filtering/filtering-test.js
  tests/unit/combo/filtering/tests.html
  tests/unit/combo/rendering/rendering-test.js
  tests/unit/combo/rendering/tests.html
  tests/unit/combo/sample-data/local-data.js
  tests/unit/combo/sample-data/remote-data.js
  tests/unit/combo/selection/selection-test.js
  tests/unit/combo/selection/tests.html
  tests/unit/combo/test-shared.js
  tests/unit/combo/virtualization/tests.html
  tests/unit/combo/virtualization/virtualization-test.js
  tests/unit/common/test-util.js
  tests/unit/editors/maskEditor/mask-test.js
Labels: combo, tests

#1702 Add case for JSON date format in applyOptions
  src/js/modules/infragistics.ui.editors.js
  tests/unit/editors/timePicker/timepicker-test.js
Labels: status: verified, timepicker, version: 18.2

#1710 Adding CHANGELOG.md file
  CHANGELOG.md
Labels: documentation

#1711 disable igCombo input field when igCombo is disabled
  src/js/modules/infragistics.ui.combo.js
  tests/unit/combo/rendering/tests.html
  tests/unit/combo/test-shared.js
Labels: status: verified, version: 17.2
