Repository IgniteUI/ignite-ui, pull requests merged in 2021-09, with the labels that each got.

#2142 docs(*): remove jquery version from docs #2118
  src/js/extensions/infragistics.ui.combo.knockout-extensions.js
  src/js/extensions/infragistics.ui.editors.knockout-extensions.js
  src/js/extensions/infragistics.ui.tree.knockout-extensions.js
  src/js/modules/infragistics.datasource.js
  src/js/modules/infragistics.templating.js
  src/js/modules/infragistics.ui.colorpicker.js
  src/js/modules/infragistics.ui.colorpickersplitbutton.js
  src/js/modules/infragistics.ui.combo.js
  src/js/modules/infragistics.ui.dialog.js
  src/js/modules/infragistics.ui.editors.js
  src/js/modules/infragistics.ui.htmleditor.js
  src/js/modules/infragistics.ui.layoutmanager.js
  src/js/modules/infragistics.ui.notifier.js
  src/js/modules/infragistics.ui.popover.js
  src/js/modules/infragistics.ui.rating.js
  src/js/modules/infragistics.ui.scroll.js
  src/js/modules/infragistics.ui.shared.js
  src/js/modules/infragistics.ui.splitbutton.js
  src/js/modules/infragistics.ui.splitter.js
  src/js/modules/infragistics.ui.tilemanager.js
  src/js/modules/infragistics.ui.toolbar.js
  src/js/modules/infragistics.ui.toolbarbutton.js
  src/js/modules/infragistics.ui.tree.js
  src/js/modules/infragistics.ui.upload.js
  src/js/modules/infragistics.ui.validator.js
  src/js/modules/infragistics.ui.videoplayer.js
  src/js/modules/infragistics.ui.widget.js
  src/js/modules/infragistics.ui.zoombar.js
  src/js/modules/infragistics.util.jquery.js
Labels: documentation, version: 21.2

#2147 Add Norwegian language - 20.2
  build/packages/combined-files.js
  src/js/modules/i18n/infragistics.datasource-nb.js
  src/js/modules/i18n/infragistics.shared-nb.js
  src/js/modules/i18n/infragistics.templating-nb.js
  src/js/modules/i18n/infragistics.ui.combo-nb.js
  src/js/modules/i18n/infragistics.ui.dialog-nb.js
  src/js/modules/i18n/infragistics.ui.editors-nb.js
  src/js/modules/i18n/infragistics.ui.htmleditor-nb.js
  src/js/modules/i18n/infragistics.ui.notifier-nb.js
  src/js/modules/i18n/infragistics.ui.popover-nb.js
  src/js/modules/i18n/infragistics.ui.rating-nb.js
  src/js/modules/i18n/infragistics.ui.scroll-nb.js
  src/js/modules/i18n/infragistics.ui.splitter-nb.js
  src/js/modules/i18n/infragistics.ui.tilemanager-nb.js
  src/js/modules/i18n/infragistics.ui.toolbar-nb.js
  src/js/modules/i18n/infragistics.ui.tree-nb.js
  src/js/modules/i18n/infragistics.ui.upload-nb.js
  src/js/modules/i18n/infragistics.ui.validator-nb.js
  src/js/modules/i18n/infragistics.ui.videoplayer-nb.js
  src/js/modules/i18n/infragistics.ui.zoombar-nb.js
  src/js/modules/i18n/infragistics.util-nb.js
Labels: enhancement, status: localized, version: 20.2

#2150 Add Norwegian language - 20.1
  build/packages/combined-files.js
  src/js/modules/i18n/infragistics.datasource-nb.js
  src/js/modules/i18n/infragistics.shared-nb.js
  src/js/modules/i18n/infragistics.templating-nb.js
  src/js/modules/i18n/infragistics.ui.combo-nb.js
  src/js/modules/i18n/infragistics.ui.dialog-nb.js
  src/js/modules/i18n/infragistics.ui.editors-nb.js
  src/js/modules/i18n/infragistics.ui.htmleditor-nb.js
  src/js/modules/i18n/infragistics.ui.notifier-nb.js
  src/js/modules/i18n/infragistics.ui.popover-nb.js
  src/js/modules/i18n/infragistics.ui.rating-nb.js
  src/js/modules/i18n/infragistics.ui.scroll-nb.js
  src/js/modules/i18n/infragistics.ui.splitter-nb.js
  src/js/modules/i18n/infragistics.ui.tilemanager-nb.js
  src/js/modules/i18n/infragistics.ui.toolbar-nb.js
  src/js/modules/i18n/infragistics.ui.tree-nb.js
  src/js/modules/i18n/infragistics.ui.upload-nb.js
  src/js/modules/i18n/infragistics.ui.validator-nb.js
  src/js/modules/i18n/infragistics.ui.videoplayer-nb.js
  src/js/modules/i18n/infragistics.ui.zoombar-nb.js
  src/js/modules/i18n/infragistics.util-nb.js
Labels: enhancement, status: localized, version: 20.1

#2148 Add Norwegian language - 21.1
  build/packages/combined-files.js
  src/js/modules/i18n/infragistics.datasource-nb.js
  src/js/modules/i18n/infragistics.shared-nb.js
  src/js/modules/i18n/infragistics.templating-nb.js
  src/js/modules/i18n/infragistics.ui.combo-nb.js
  src/js/modules/i18n/infragistics.ui.dialog-nb.js
  src/js/modules/i18n/infragistics.ui.editors-nb.js
  src/js/modules/i18n/infragistics.ui.htmleditor-nb.js
  src/js/modules/i18n/infragistics.ui.notifier-nb.js
  src/js/modules/i18n/infragistics.ui.popover-nb.js
  src/js/modules/i18n/infragistics.ui.rating-nb.js
  src/js/modules/i18n/infragistics.ui.scroll-nb.js
  src/js/modules/i18n/infragistics.ui.splitter-nb.js
  src/js/modules/i18n/infragistics.ui.tilemanager-nb.js
  src/js/modules/i18n/infragistics.ui.toolbar-nb.js
  src/js/modules/i18n/infragistics.ui.tree-nb.js
  src/js/modules/i18n/infragistics.ui.upload-nb.js
  src/js/modules/i18n/infragistics.ui.validator-nb.js
  src/js/modules/i18n/infragistics.ui.videoplayer-nb.js
  src/js/modules/i18n/infragistics.ui.zoombar-nb.js
  src/js/modules/i18n/infragistics.util-nb.js
Labels: enhancement, status: localized, version: 21.1

#2149 Add Norwegian language - 21.2
  build/packages/combined-files.js
  src/js/modules/i18n/infragistics.datasource-nb.js
  src/js/modules/i18n/infragistics.shared-nb.js
  src/js/modules/i18n/infragistics.templating-nb.js
  src/js/modules/i18n/infragistics.ui.combo-nb.js
  src/js/modules/i18n/infragistics.ui.dialog-nb.js
  src/js/modules/i18n/infragistics.ui.editors-nb.js
  src/js/modules/i18n/infragistics.ui.htmleditor-nb.js
  src/js/modules/i18n/infragistics.ui.notifier-nb.js
  src/js/modules/i18n/infragistics.ui.popover-nb.js
  src/js/modules/i18n/infragistics.ui.rating-nb.js
  src/js/modules/i18n/infragistics.ui.scroll-nb.js
  src/js/modules/i18n/infragistics.ui.splitter-nb.js
  src/js/modules/i18n/infragistics.ui.tilemanager-nb.js
  src/js/modules/i18n/infragistics.ui.toolbar-nb.js
  src/js/modules/i18n/infragistics.ui.tree-nb.js
  src/js/modules/i18n/infragistics.ui.upload-nb.js
  src/js/modules/i18n/infragistics.ui.validator-nb.js
  src/js/modules/i18n/infragistics.ui.videoplayer-nb.js
  src/js/modules/i18n/infragistics.ui.zoombar-nb.js
  src/js/modules/i18n/infragistics.util-nb.js
Labels: enhancement, status: localized, version: 21.2

#2151 Add GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/npm-publish.yml
  .travis.yml
  README.md
  karma.conf.js
  package-lock.json
  package.json
  tests/unit/editors/DatePickerBugs/datePickerBugs-test.js
  tests/unit/editors/maskEditor/mask-test.js
  tests/unit/editors/percentEditor/percent-test.js
  tests/unit/editors/textEditor/textEditor-test.js
  tests/unit/scroll/scroll-test.js
Labels: version: 20.2

#2152 Add GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/node.js.yml
  .github/workflows/npm-publish.yml
  .travis.yml
  README.md
  karma.conf.js
  package-lock.json
  package.json
  tests/unit/editors/DatePickerBugs/datePickerBugs-test.js
  tests/unit/editors/maskEditor/mask-test.js
  tests/unit/editors/percentEditor/percent-test.js
  tests/unit/editors/textEditor/textEditor-test.js
  tests/unit/scroll/scroll-test.js
Labels: version: 20.1
